config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
  resources :members, only: [:new, :create]
  namespace :admin do
    resources :members, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  DEPARTMENTS = %w(财务系统 综训及户外事业部 质量管理中心 信息技术系统 鞋研开发生产中心
                  销售系统 人力资源系统 品牌项目管理中心 跑步事业部 篮羽事业部 韩国设计中心
                  服研开发生产中心 电子商务部 品牌设计部).freeze
  SIZES = %w(L（175以下） XXL（175-185） XXXL（185以上） 儿童120 儿童150).freeze
  FAMILY_AMOUNTS = %w(0 1 2).freeze
  ANNIVERSARIES = %w(25 26 从没参加过).freeze
  BUS_LINE = %w(1号线（四季青桥-李宁公司） 2号线（公主坟-李宁公司） 3号线（崇文门-李宁公司）
              4号线（右安门-李宁公司） 5号线（罗马园-李宁公司） 6号线（望京地铁-李宁公司）
              7号线（管庄-李宁公司） 8号线（通州北苑-李宁公司） 9号线（中关村-李宁公司）
              10号线（北太平庄-李宁公司）).freeze

  attr_accessor :family_sizes1
  attr_accessor :family_sizes2
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def admin?
    is_admin
  end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < AdminController
  def index
    @members = Member.all
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :require_is_admin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :mobile_device?, :phone_device?

  def require_is_admin
    return if current_user.admin?
    flash[:alert] = "你没有管理员权限"
    redirect_to root_path
  end

  def mobile_device?
    @mobile_device ||= (browser.device.mobile? || browser.device.tablet?) && cookies[:platform] != 'web'
  end

  def phone_device?
    @phone_device ||= browser.device.mobile?
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout 'publish'
  
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  layout 'publish'

  def new
    @member = Member.new
  end

  def create
    Member.create member_params
    redirect_to root_path
  end

  private

  def member_params
    if params[:member][:family_sizes1]
      params[:member][:sizes] |= params[:member][:family_sizes1]
    end
    if params[:member][:family_sizes2]
      params[:member][:sizes] |= params[:member][:family_sizes2]
    end
    params.require(:member).permit(:name, :department, :employee_code, :family_amount, :shuttle_bus, :bus_line, anniversaries: [], sizes: [], family_sizes1: [], family_sizes2: [])
  end
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/application_helper.rb
JS_VOID = 'javascript:void(0)'.freeze

module ApplicationHelper
  def layout_helper_class
    class_name = " #{controller_name}-#{action_name}-page"
    class_name += ' mobile-device' if mobile_device?
    class_name += ' phone-device' if phone_device?
    class_name += ' browser-firefox' if browser.firefox?
    class_name
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/admin/members/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">报名人员列表</div>

  <table class="table">
    <thead>
      <th>员工姓名</th>
      <th>员工编号</th>
      <th>班车路线</th>
    </thead>
    <tbody>
      <% @members.each do |member|  %>
        <tr>
          <td><%= member.name %></td>
          <td><%= member.employee_code %></td>
          <td><%= member.bus_line %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid navbar-container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">司庆</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if !current_user %>
            <li><%= link_to("注册", new_user_registration_path) %> </li>
            <li><%= link_to("登录", new_user_session_path) %></li>
          <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                 Hi!, <%= current_user.email %>
                 <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li> <%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>
              </ul>
            </li>
          <% end %>
        </ul>
    </div>
  </div>
</nav>

app/views/dashboard/index.html.erb
<div class="dashboard">
  <%= render 'shared/banner' %>
  <div class="container">
    <div class="row center">
      <div class="content-section col-xs-12">
        <div class="section-header">
        </div>
        <div class="section-body">
          <div class="btn-group">
            <%= link_to '司庆报名', new_member_path, class: 'btn btn-primary' %>
            <%= link_to '登录', JS_VOID, class: 'btn btn-primary' %>
            <%= link_to '照片下载', JS_VOID, class: 'btn btn-primary' %>
            <%= link_to '司庆大事记', JS_VOID, class: 'btn btn-primary' %>
            <%= link_to '游戏介绍', JS_VOID, class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag('favicon.ico') %>
    <title>celebrate_company</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= layout_helper_class %>">
    <%= render 'common/navbar' %>
    <div class="admin-container container">
      <div class="col-md-10 col-md-offset-1">
        <%= render "common/flashes" %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag('favicon.ico') %>
    <title>celebrate_company</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= layout_helper_class %>">
    <div class="app-container">
      <%= render 'common/navbar' %>
      <%= render "common/flashes" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/publish.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag('favicon.ico') %>
    <title>celebrate_company</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= layout_helper_class %>">
    <div class="app-publish-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/members/new.erb
<div class="member-container">
  <%= render 'shared/banner' %>
  <div class="container">
    <%= form_for @member, html: {class: 'member-form center'} do |f| %>
      <div class="form-header container-fluid">
        <div class="row">
          <h1 class="form-title col-md-12 font-family-inherit">
            李宁26周年嘉年华报名平台
          </h1>
          <div class="form-description col-md-12">
            <p>如因天气等原因影响活动正常进行，将提前通知调整时间！</p>
          </div>
        </div>
      </div>
      <div class="form-content container-fluid">
        <div class="row">
            <div class="fields clearfix">
              <div class="field field-drop-down col-sm-12 required">
                <div class="form-group">
                  <%= f.label :department, '系统', class: 'field-label' %>
                  <%= f.select :department, options_for_select(['请选择']|Member::DEPARTMENTS, ""), {}, {class: 'form-control'}  %>
                </div>
              </div>
              <div class="field field-text-field col-sm-12 required">
                <div class="form-group">
                  <%= f.label :employee_code, '员工编号', class: 'field-label' %>
                  <span class="field-description">请正确输入您的员工编号</span>
                  <%= f.text_field :employee_code, class: 'form-control' %>
                </div>
              </div>
              <div class="field field-text-field col-sm-12 required">
                <div class="form-group">
                  <%= f.label :name, '员工姓名', class: 'field-label' %>
                  <%= f.text_field :name, class: 'form-control' %>
                </div>
              </div>
              <div class="field field-radio-button col-sm-12 required">
                <div class="form-group">
                  <%= f.label :name, '服装尺码', class: 'field-label' %>
                  <div class="choices">
                    <% Member::SIZES.each do |size| %>
                      <label class="radio ">
                        <div class="radio-button-wrapper">
                          <%= f.radio_button :sizes, size, {multiple: true} %>
                          <i class="selected-icon"></i>
                        </div>
                        <div class="choice-description">
                          <%= size %>
                        </div>
                      </label>
                    <% end %>
                  </div>
                </div>
              </div>

              <div class="field field-radio-button col-sm-12 required logic-trigger">
                <div class="form-group">
                  <%= f.label :name, '携带家属数量', class: 'field-label' %>
                  <span class="field-description">每名员工可携带两名直系亲属参加活动（如家庭中有两名儿童可联系系统助理线下申请一名弹性名额）</span>
                  <div class="choices">
                    <% Member::FAMILY_AMOUNTS.each do |family_amount| %>
                      <label class="radio ">
                        <div class="radio-button-wrapper">
                          <%= f.radio_button :family_amount, family_amount %>
                          <i class="selected-icon"></i>
                        </div>
                        <div class="choice-description">
                          <%= family_amount %>
                        </div>
                      </label>
                    <% end %>
                  </div>
                </div>
              </div>

              <div class="field field-radio-button col-sm-12 hide" id="family_sizes1">
                <div class="form-group">
                  <%= f.label :name, '服装尺码', class: 'field-label' %>
                  <div class="choices">
                    <% Member::SIZES.each do |size| %>
                      <label class="radio ">
                        <div class="radio-button-wrapper">
                          <%= f.radio_button :family_sizes1, size, {multiple: true} %>
                          <i class="selected-icon"></i>
                        </div>
                        <div class="choice-description">
                          <%= size %>
                        </div>
                      </label>
                    <% end %>
                  </div>
                </div>
              </div>

              <div class="field field-radio-button col-sm-12 hide" id="family_sizes2">
                <div class="form-group">
                  <%= f.label :name, '服装尺码', class: 'field-label' %>
                  <% Member::SIZES.each do |size| %>
                    <label class="radio ">
                      <div class="radio-button-wrapper">
                        <%= f.radio_button :family_sizes2, size, {multiple: true} %>
                        <i class="selected-icon"></i>
                      </div>
                      <div class="choice-description">
                        <%= size %>
                      </div>
                    </label>
                  <% end %>
                </div>
              </div>

              <div class="field field-radio-button col-sm-12 required">
                  <div class="form-group">
                    <%= f.label :name, '是否参加过司庆', class: 'field-label' %>
                    <div class="choices">
                      <% Member::ANNIVERSARIES.each do |anniversarie| %>
                        <label class="checkbox">
                          <div class="check-box-wrapper">
                            <%= f.check_box :anniversaries, {multiple: true}, anniversarie, nil %>
                            <i class="selected-icon"></i>
                          </div>
                          <div class="choice-description">
                            <%= anniversarie %>
                          </div>
                        </label>
                      <% end %>
                    </div>
                  </div>
                </div>

                <div class="field field-radio-button col-sm-12 required">
                  <div class="form-group">
                    <%= f.label :name, '是否乘坐班车', class: 'field-label' %>
                    <div class="choices">
                      <label class="radio ">
                        <div class="radio-button-wrapper">
                          <%= f.radio_button :shuttle_bus, true %>
                          <i class="selected-icon"></i>
                        </div>
                        <div class="choice-description">
                          是
                        </div>
                      </label>
                      <label class="radio ">
                        <div class="radio-button-wrapper">
                          <%= f.radio_button :shuttle_bus, false %>
                          <i class="selected-icon"></i>
                        </div>
                        <div class="choice-description">
                          否
                        </div>
                      </label>
                    </div>
                  </div>
                </div>
                <div class="field field-drop-down col-sm-12 hide required">
                  <div class="form-group">
                    <%= f.label :bus_line, '乘坐班车路线', class: 'field-label' %>
                    <%= f.select :bus_line, options_for_select(['请选择']|Member::BUS_LINE, ""), {}, {class: 'form-control'}  %>
                  </div>
                </div>
            </div>
            <div class="field submit-field col-md-12 clearfix pull-right">
              <input type="button" name="commit" value="提交" data-disable-with="提交中..." data-enable-with="提交" class="submit btn btn-primary-solid">
            </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner center">
  <div class="banner-img">
    <%= image_tag 'dashboard/lining.jpeg', class: 'header-image need-adapt-retina' %>
  </div>
</div>